name: Keep Repo Alive

on:
  schedule:
    - cron: "0 */10 * * *"  # Elke 10 uur
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Maak lege commit
        run: |
          git commit --allow-empty -m "🕒 Keep-alive commit"

      - name: Push commit
        run: git push origin main
